declare module 'element-ui/lib/utils/date-util'
declare module 'element-ui/lib/locale'
declare module 'element-ui/lib/utils/util'
declare module 'element-ui/lib/utils/resize-event'
declare module 'throttle-debounce'
